version: "3"

services:
  test-demo-5-api:
    build:
      context: test_demo_5_api
    ports:
      - "8080:8080"
  test-demo-5-ui:
    build:
      context: test-demo-5-ui
      args:
        APP_SERVER_HOST: localhost
        APP_SERVER_PORT: 8080
    ports:
      - "80:80"
    depends_on:
      - test-demo-5-api
    links:
      - test-demo-5-api
